// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/Users/VincentX/Dev/Project/dumi/dumi-theme-legecy/node_modules/.pnpm/dumi@2.0.18_wnhobytbzuxeuvkr3fshiwzzla/node_modules/dumi/theme-default/slots/HeadeExtra/index.js';
